M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu20.04.1} date Wed 01 May 2024 22:26:14 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-01T22:26:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.905
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X87.911Y-85.79
X87.911Y-91.57
T2
X94.731Y-73.606
X94.731Y-78.0
T3
X84.9Y-63.25
X84.9Y-114.725
X160.4Y-63.25
X160.4Y-114.75
M30
