#!/bin/sh

mount -t sysfs none /sys
mount proc /proc -t proc
mount -o remount,noatime,rw /
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/libexec/gcc/riscv32-unknown-linux-gnu/13.2.0
export PS1='\u:\[\e[34m\]\w\[\e[m\]\$ '
export LC_ALL=C.UTF-8
export GROFF_TYPESETTER=ascii

/usr/bin/textwm &
sleep 1

twmrun 1 sh
twmrun 2 sh

sh
